### ISSUE TITLE
Servereinstellungen nach Veranstaltungskategorien konfigurieren

### ISSUE THREAD

**Issue by sys-cr** [virtUOS/studip-meeting#218] opened 2021-03-25 14:27 UTC
Folgende Änderungen wären wünschenswert:

- Konfigurationsmöglichkeit im Backend für Server, um Studip-Veranstaltungskategorien (sem_classes) an einen Server zu binden.
    - Konfigurationsoption z.B. "Nur in folgenden Veranstaltungskategorien nutzbar" (Default: alle); Checkbox-Auswahl
    - Es soll z.B. für Studiengruppen nur möglich sein, einen von mehreren konfigurierten Servern (bzw. Loadbalancern) zu nutzen.
- Deaktivierbare Servereinträge im Backend

**Comment by ferishili** [comment] 2021-04-01 14:23
@sys-cr, since you have the use-case, is it possible for you to have an in-depth test for this feature?

**Comment by sys-cr** [comment] 2021-04-06 08:54
@ferishili: Yes, should be possible at our Stud.IP-testing system at Leibniz University.

**Comment by ferishili** [comment] 2021-04-06 08:56
Great, how do you prefer to get the beta version zip file? Or should I install it on that test server?

**Comment by sys-cr** [comment] 2021-04-06 09:03
@ferishili and @crosscodr maybe you two can get in touch?

**Comment by crosscodr** [comment] 2021-04-06 09:31
Hi @ferishili, we deploy our plugins to the testserver with git directly. We maintain a fork of this repository. So the best solution would be a feature branch.

**Comment by ferishili** [comment] 2021-04-06 10:03
Hi @crosscodr, I have created a new branch (https://github.com/virtUOS/studip-meeting/tree/beta_test), please try it out and let me know if it works fine!

**Comment by sys-cr** [comment] 2021-04-06 10:06
@ferishili: thank you! we will let you know!

**Comment by crosscodr** [comment] 2021-04-09 08:53
Hi @ferishili, the feature looks good to us :)
The only little improvement we would suggest, is the following. When creating a new meeting room, the user has to select one server, even if there is only one choice. In this case, the plugin could automatically choose the only available server. But thats a little one.
Thank you for the feature :)

**Comment by ferishili** [comment] 2021-04-09 08:56
Hi @crosscodr, thank you for your feedback, I will get it done.

**Comment by ferishili** [comment] 2021-04-12 08:37
> Hi @ferishili, the feature looks good to us :)
> The only little improvement we would suggest, is the following. When creating a new meeting room, the user has to select one server, even if there is only one choice. In this case, the plugin could automatically choose the only available server. But thats a little one.
> Thank you for the feature :)

Hi, the feature of auto-selecting the server if there is only one available was already implemented and I could not reproduce the case you mentioned, please take a deeper look and let me know if you still have that problem! 
Note: according to your commit above I could suggest to run the command (npm run zip), in order for the plugin to use all the resource it needs. thanks.

**Comment by crosscodr** [comment] 2021-04-12 11:20
Hi @ferishili,
the use case is the following: Create a new meeting-room. Then one can select a Driver, e.g. BBB. Now, the choice in "select server" field is not autoselected, even if there is only one server for this course-category. You have to test it at least with two servers; one selectable in the current course and another, which is not allowed in the course.
It's a little one, though.

> Note: according to your commit above I could suggest to run the command (npm run zip), in order for the plugin to use all the resources it needs. thanks.
Yes, I put the contents of the zip in an extra branch to deploy it directly.

**Comment by ferishili** [comment] 2021-04-12 14:20
@crosscodr the complete feature with auto-select is merged into master, please have a look. Thank you for your productive request!

**Closed** 2021-04-12 14:21 UTC

**Comment by crosscodr** [comment] 2021-04-12 15:03
Thanks a lot! @ferishili
